services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    restart: always
    volumes:
      - ./data:/root
    network_mode: "host"
    depends_on:
      - hbbr
  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    restart: always
    volumes:
      - ./data:/root
    network_mode: "host"
